# Generated by Django 5.1.5 on 2025-02-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                help_text="Введите описание категории",
                max_length=200,
                verbose_name="Описание категории",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите наименование категории",
                max_length=200,
                verbose_name="Наименование категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                help_text="Введите описание продукта",
                max_length=200,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование продукта",
                max_length=200,
                verbose_name="Наименование",
            ),
        ),
    ]
