# Generated by Django 5.1.5 on 2025-03-25 16:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("unpublish", "Can unpublish product"),
                    ("delete", "Can delete product"),
                    ("view", "Can view product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Укажите дату создания",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                default=datetime.datetime(
                    2025, 3, 25, 16, 17, 48, 519044, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату последнего изменения",
                verbose_name="Дата последнего изменения",
            ),
            preserve_default=False,
        ),
    ]
