# Generated by Django 5.1.5 on 2025-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_options_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_moderated",
            field=models.BooleanField(default=False, verbose_name="Модерация"),
        ),
    ]
