# Generated by Django 5.1.5 on 2025-03-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_moderated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_moderated",
        ),
    ]
