# Generated by Django 5.1.5 on 2025-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_product_is_moderated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True, verbose_name="Доступность в каталоге"
            ),
        ),
    ]
