# Generated by Django 5.1.5 on 2025-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_is_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("unpublish", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=False, verbose_name="Доступность в каталоге"
            ),
        ),
    ]
